name: Check code quality
on:
  pull_request:

jobs:
  check-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check flake8
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .